include:
  - project: 'ucode/ops/ci-cd'
    ref: master
    file: 'microfrontend/ci.gitlab-ci.yml'

  - project: 'ucode/ops/ci-cd'
    ref: master
    file: 'microfrontend/cd.gitlab-ci.yml'

stages:
  - build
  - deploy
